version: "3.8"

services:
  postgres:
    image: postgres:13.2-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    hostname: postgres
    restart: always

  pgadmin:
    image: dpage/pgadmin4:5.2
    container_name: pgadmin
    ports:
      - 8000:80
    volumes:
      - ./docker/pgadmin/data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: root@test.com
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin
    depends_on:
      - postgres
    restart: always
